# Tasks to converge to state absent
---
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Remove package
  ansible.builtin.package:
    name: "{{ package }}"
    state: absent

- name: Remove documents
  ansible.builtin.file:
    path: "{{ webroot }}"
    state: absent
