# Tasks to reach desired state present
---
- name: Manage package
  ansible.builtin.package:
    name: "{{ package }}"
    state: "{{ desired_state }}"
    update_cache: true
  notify: Control service

- name: Enable service
  ansible.builtin.systemd:
    name: "{{ service }}"
    enabled: true
    daemon_reload: true
  notify: Control service

- name: Instal homepage
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
