# Tasks to reach desired_state: present
---
- name: Manage dependencies
  ansible.builtin.package:
    name: "{{ dependencies }}"
    state: "{{ desired_state }}"
    update_cache: true

- name: Manage package
  ansible.builtin.package:
    name: "{{ package }}"
    state: "{{ desired_state }}"
  notify: Control service

- name: Enable service
  ansible.builtin.systemd:
    name: "{{ service }}"
    enabled: true
    daemon_reload: true
  notify: Control service

- name: Check clone in webroot
  ansible.builtin.git:
    repo: "{{ webrepo }}"
    dest: "{{ webroot }}/"
    version: main
    clone: false
    update: false
  register: clone

- name: Update webrepo in webroot
  block:
    - name: Delete webroot
      ansible.builtin.file:
        path: "{{ webroot }}"
        state: absent
    - name: Clone webrepo in webroot
      ansible.builtin.git:
        repo: "{{ webrepo }}"
        dest: "{{ webroot }}/"
        version: main
  when: clone.before != clone.after
