# Tasks to reach desired_state: present
---
- name: Manage dependencies
  ansible.builtin.package:
    name: "{{ dependencies }}"
    state: "{{ desired_state }}"
    update_cache: true

- name: Manage package
  ansible.builtin.package:
    name: "{{ package }}"
    state: "{{ desired_state }}"
  notify: Control service

- name: Enable service
  ansible.builtin.systemd:
    name: "{{ service }}"
    enabled: true
    daemon_reload: true
  notify: Control service

- name: Check homepage
  ansible.builtin.stat:
    path: "{{ webroot }}/index.html"
  register: homepage

- name: Install webrepo
  block:
    - name: Remove documents
      ansible.builtin.file:
        path: "{{ webroot }}"
        state: absent

    - name: Install webrepo in webroot
      ansible.builtin.git:
        repo: "{{ webrepo }}"
        dest: "{{ webroot }}/"
        single_branch: true
        version: main

    - name: Ensure webroot exists
      ansible.builtin.file:
        path: "{{ webroot }}"
        owner: root
        group: root
        mode: '0755'
        recurse: true
  when: homepage.stat.readable is not defined
