# This is an example playbook to execute Ansible tests.
---
- name: Cleanup
  hosts: all
  gather_facts: false
  vars:
    desired_state: "absent"
    role_name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
  tasks:
    - name: "Include nginx"
      ansible.builtin.include_role:
        name: "{{ role_name }}"
