# This is an example playbook to execute Ansible tests.
---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include nginx"
      ansible.builtin.include_role:
        name: "nginx"
