---
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy

dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: podman

platforms:
  - name: ubi8
    image: registry.access.redhat.com/ubi8/ubi-init
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/usr/sbin/init"

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer
    ssh_connection:
      pipelining: false

lint: |
  set -e
  yamllint .
  ansible-lint

verifier:
  name: ansible
