---
# Molecule configuration
# https://molecule.readthedocs.io/en/latest/

driver:
  name: docker

platforms:
  - name: ubi8
    image: registry.access.redhat.com/ubi8/ubi-init
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/usr/sbin/init"
    capabilities:
      - NET_BIND_SERVICE
    published_ports:
      - 127.0.0.1:8000:80

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer

lint: |
  set -e
  yamllint .
  ansible-lint

verifier:
  name: ansible
